version: '3.8'
services:
  node:
    build: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - dev-db

  dev-db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - rsschoollena

networks:
  rsschoollena:
    name: rsschoollena
    driver: bridge